### ISSUE TITLE
Check DenoGres or Kysely query builder

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/fresh-spots#4]
https://denogres.deno.dev/docs/getting-started

**Comment by omar2205** [comment]
Or check this example
https://github.com/michalvavra/fresh-sqlite-example using [SQLite](https://www.sqlite.org/) and [kysely](https://koskimas.github.io/kysely/) query builder

**Comment by omar2205** [comment]
A working Postgres Driver for Kysely
https://gist.github.com/omar2205/cd42feccf25cff845b50ec2397eba18f

**Comment by w3cj** [comment]
Thanks for the suggestions. I'll probably end up using Kysely since I'm so familiar with knex and I won't have to figure out how to work with another half finished ORM.

**Comment by w3cj** [comment]
🙏 Thanks again for these suggestions. Closing to clean up for now.
