### ISSUE TITLE
Something something... I made diz squishy_cookies

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/fresh-spots#7]
Check this 
https://github.com/omar2205/squishy_cookies

**Comment by omar2205** [comment]
There is this method where you set a field in the table:
```
User table = {
  // ...
  login: 1
}
```
And you use it like this:
```
await createSignedCookie('id', `${user.id}:${user.login}`, ....)
```

And to invalidate the cookie just increase that number

**Comment by w3cj** [comment]
It's beautiful! I slept on it and decided I was going to create this if someone didn't. The `RequestCookieStore` and `SignedCookieStore` just don't seem quite right for what we need here.
