### ISSUE TITLE
Enabling tailwind Intellisense

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/fresh-spots#8]
1. Install https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss
2. Install https://marketplace.visualstudio.com/items?itemName=sastan.twind-intellisense
3. Create an empty file named `twind.config.js`

**Comment by timondev** [comment]
Add a tailwind.config.js file:

```
/* @type {import('tailwindcss').Config} */
module.exports = {
  theme: {},
  plugins: []
}
```

**Comment by SalahuddinAhammed** [comment]
Alternatively, you can run `npx tailwindcss init`. It will generate the `tailwind.config.js` file.

**Comment by omar2205** [comment]
Empty `tailwind.config.js` or `twind.config.js` will do. `/* @type {import('tailwindcss').Config} */` was causing problems because it tried to import `tailwindcss`. Most configurations will be in `utils/twind.ts`
